name: Vaping Eliquids
favicon: null
layout_spectrum: 0.4532209096942097
typography_spectrum: 0.8099865457043052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9329243209213018
  lightness: 0.5161762700881809
  saturation: 0.3134071915410459
  rhythmicContrast: 0.9070295139681548
purpose: []
